/**
 * A document this engine wrote, saying so in itself (FR-017, FR-020).
 *
 * A build takes away what it no longer compiles, and where it looks is a
 * directory a host reads — the same directory someone may have written a command
 * or a skill of their own into, by hand, long before a charter was ever built
 * here. A path is not enough to tell the two apart, and guessing wrong destroys
 * someone's work. So a file this build puts down carries a stamp, and a build
 * deletes nothing that does not.
 *
 * It doubles as what a reader needs: a compiled file someone opens says where to
 * go and change it, rather than being edited into something the next build
 * undoes.
 *
 * Only what is written as prose can carry one. A listing is JSON and has nowhere
 * to say it, and a host's settings file is the repository's as much as this
 * engine's — those two are known by where they are instead.
 */
export const GENERATED_STAMP = "Generated by cherry-works";

/** The text of one document that carries the stamp. Text, and said as its own
 *  type: what a projection writes is a document this engine will know again, and
 *  a plain string is what it is written as rather than what it is. */
export type StampedDocument = string;

/**
 * One document with the stamp on the end of it.
 *
 * The one way any output of this engine becomes the text of a document, so every
 * one of them carries the stamp and none of them has to remember to. What the
 * document says above it is whoever compiled it; this adds the line and nothing
 * else.
 */
export function stamp(document: string): StampedDocument {
  return `${document.replace(/\n+$/, "")}\n\n<!-- ${GENERATED_STAMP}. Do not edit; edit the charter and build again. -->\n`;
}

/** Did this build, or one before it, write this file? Asked of what is on disk
 *  before anything is taken away. */
export function isStamped(contents: string): boolean {
  return contents.includes(GENERATED_STAMP);
}
